#!/bin/bash

# Tested on Ubuntu 12.04 and PulseAudio. 
# Since Unity or Gnome has direct support for volume control, you won't need this unless you use other windows manager, e.g. i3. 
# Try `pactl list` to see the list of sinks you own, or try `toggle_mute 0` `toggle_mute 1` one by one.


if [ "$#" = "1" ]
then 
    FORMAT='$0~"Sink"{start=0} $0~"Sink #'"$1"'"{start=1} $1~"Mute"&&start {print $2~"no"}'
    pactl list sinks | awk "$FORMAT" | xargs pactl set-sink-mute $1
else
    echo "USAGE: $0 <sink id>"
fi
